/*
 * Anushtanam content data.
 *
 * HOW TO ADD YOUR OWN CONTENT
 * ---------------------------
 * Each item has parallel "telugu" and "english" arrays. Line 1 of telugu is
 * shown, and line 1 of english (phonetic transliteration) is shown directly
 * BELOW it. Line 2 pairs with line 2, and so on.
 *
 * Keep telugu[] and english[] the SAME LENGTH so pairs stay aligned.
 * Type the text EXACTLY as you want it read, including any markings
 * (svara dots, underscores, IAST diacritics like a a i i m n ...).
 * Do NOT add hyphens between syllables.
 *
 * `meaning` (optional) is shown as a separate block under the verse.
 * `daily` lists item ids to show on the Today view, in order.
 *
 * NOTE: Texts below are SAMPLE PLACEHOLDERS to show the layout. Replace them.
 */

const ANUSHTANAM = {
  daily: ["sri-suktam", "purusha-suktam", "gayatri"],

  categories: [
    {
      id: "sandhya",
      title: "\u0c38\u0c02\u0c27\u0c4d\u0c2f\u0c3e\u0c35\u0c02\u0c26\u0c28\u0c02",
      titleEn: "Sandhyavandanam",
      items: [
        {
          id: "gayatri",
          title: "\u0c17\u0c3e\u0c2f\u0c24\u0c4d\u0c30\u0c40 \u0c2e\u0c02\u0c24\u0c4d\u0c30\u0c02",
          titleEn: "Gayatri Mantra",
          telugu: [
            "\u0c13\u0c02 \u0c2d\u0c42\u0c30\u0c4d\u0c2d\u0c41\u0c35\u0c03 \u0c38\u0c4d\u0c35\u0c03 \u0964",
            "\u0c13\u0c02 \u0c24\u0c24\u0c4d\u0c38\u0c35\u0c3f\u0c24\u0c41\u0c30\u0c4d\u0c35\u0c30\u0c47\u0c23\u0c4d\u0c2f\u0c02",
            "\u0c2d\u0c30\u0c4d\u0c17\u0c4b \u0c26\u0c47\u0c35\u0c38\u0c4d\u0c2f \u0c27\u0c40\u0c2e\u0c39\u0c3f \u0964",
            "\u0c27\u0c3f\u0c2f\u0c4b \u0c2f\u0c4b \u0c28\u0c03 \u0c2a\u0c4d\u0c30\u0c1a\u0c4b\u0c26\u0c2f\u0c3e\u0c24\u0c4d \u0965",
          ],
          english: [
            "oṁ bh\u016brbhuvaṁ svaṁ",
            "o\u1e41 tatsaviturvareṇyaṁ",
            "bhargo devasya dh\u012bmahi",
            "dhiyo yo naṁ pracoday\u0101t",
          ],
          meaning:
            "Om. Earth, atmosphere, heavens. We meditate on that adorable radiance of the divine Sun. May it inspire and guide our intellect.",
        },
      ],
    },
    {
      id: "suktam",
      title: "సూక్తములు",
      titleEn: "Suktam",
      items: [
        {
          id: "sri-suktam",
          title: "శ్రీ సూక్తం",
          titleEn: "Sri Suktam",
          note: "ఋగ్వేద ఖిల సూక్తం · Source: Stotranidhi (with svara markings).",
          telugu: [
            "హిర॑ణ్యవర్ణా॒o హరి॑ణీం సు॒వర్ణ॑రజ॒తస్ర॑జామ్ |",
            "చ॒న్ద్రాం హి॒రణ్మ॑యీం ల॒క్ష్మీం జాత॑వేదో మ॒ ఆవ॑హ || ౧ ||",
            "తాం మ॒ ఆవ॑హ॒ జాత॑వేదో ల॒క్ష్మీమన॑పగా॒మినీ”మ్ |",
            "యస్యా॒o హిర॑ణ్యం వి॒న్దేయ॒o గామశ్వ॒o పురు॑షాన॒హమ్ || ౨ ||",
            "అ॒శ్వ॒పూ॒ర్వాం ర॑థమ॒ధ్యాం హ॒స్తినా॑దప్ర॒బోధి॑నీమ్ |",
            "శ్రియ॑o దే॒వీముప॑హ్వయే॒ శ్రీర్మా॑దే॒వీర్జు॑షతామ్ || ౩ ||",
            "కా॒o సో”స్మి॒తాం హిర॑ణ్యప్రా॒కారా॑మా॒ర్ద్రాం జ్వల॑న్తీం తృ॒ప్తాం త॒ర్పయ॑న్తీమ్ |",
            "ప॒ద్మే॒ స్థి॒తాం ప॒ద్మవ॑ర్ణా॒o తామి॒హోప॑హ్వయే॒ శ్రియమ్ || ౪ ||",
            "చ॒న్ద్రాం ప్ర॑భా॒సాం య॒శసా॒ జ్వల॑న్తీ॒o శ్రియ॑o లో॒కే దే॒వజు॑ష్టాముదా॒రామ్ |",
            "తాం ప॒ద్మినీ॑మీ॒o శర॑ణమ॒హం ప్రప॑ద్యేఽల॒క్ష్మీర్మే॑ నశ్యతా॒o త్వాం వృ॑ణే || ౫ ||",
            "ఆ॒ది॒త్యవ॑ర్ణే॒ తప॒సోఽధి॑జా॒తో వన॒స్పతి॒స్తవ॑ వృ॒క్షోఽథ బి॒ల్వః |",
            "తస్య॒ ఫలా॑ని॒ తప॒సా ను॑దన్తు మా॒యాన్త॑రా॒యాశ్చ॑ బా॒హ్యా అ॑ల॒క్ష్మీః || ౬ ||",
            "ఉపై॑తు॒ మాం దే॑వస॒ఖః కీ॒ర్తిశ్చ॒ మణి॑నా స॒హ |",
            "ప్రా॒దు॒ర్భూ॒తోఽస్మి॑ రాష్ట్రే॒ఽస్మిన్ కీ॒ర్తిమృ॑ద్ధిం ద॒దాతు॑ మే || ౭ ||",
            "క్షుత్పి॑పా॒సామ॑లాం జ్యే॒ష్ఠామ॑ల॒క్ష్మీం నా॑శయా॒మ్యహమ్ |",
            "అభూ॑తి॒మస॑మృద్ధి॒o చ సర్వా॒o నిర్ణు॑ద మే॒ గృహా॑త్ || ౮ ||",
            "గ॒oధ॒ద్వా॒రాం దు॑రాధ॒ర్షా॒o ని॒త్యపు॑ష్టాం కరీ॒షిణీ”మ్ |",
            "ఈ॒శ్వరీ॑గ్ం సర్వ॑భూతా॒నా॒o తామి॒హోప॑హ్వయే॒ శ్రియమ్ || ౯ ||",
            "మన॑స॒: కామ॒మాకూ॑తిం వా॒చః స॒త్యమ॑శీమహి |",
            "ప॒శూ॒నాం రూ॒పమన్న॑స్య॒ మయి॒ శ్రీః శ్ర॑యతా॒o యశ॑: || ౧౦ ||",
            "క॒ర్దమే॑న ప్ర॑జాభూ॒తా॒ మ॒యి॒ సంభ॑వ క॒ర్దమ |",
            "శ్రియ॑o వా॒సయ॑ మే కు॒లే మా॒తర॑o పద్మ॒మాలి॑నీమ్ || ౧౧ ||",
            "ఆప॑: సృ॒జన్తు॑ స్ని॒గ్ధా॒ని॒ చి॒క్లీ॒త వ॑స మే॒ గృహే |",
            "ని చ॑ దే॒వీం మా॒తర॒o శ్రియ॑o వా॒సయ॑ మే కు॒లే || ౧౨ ||",
            "ఆ॒ర్ద్రాం పు॒ష్కరి॑ణీం పు॒ష్టి॒o పి॒ఙ్గ॒లాం ప॑ద్మమా॒లినీమ్ |",
            "చ॒న్ద్రాం హి॒రణ్మ॑యీం ల॒క్ష్మీం జాత॑వేదో మ॒ ఆవ॑హ || ౧౩ ||",
            "ఆ॒ర్ద్రాం య॒: కరి॑ణీం య॒ష్టి॒o సు॒వ॒ర్ణాం హే॑మమా॒లినీమ్ |",
            "సూ॒ర్యాం హి॒రణ్మ॑యీం ల॒క్ష్మీ॒o జాత॑వేదో మ॒ ఆవహ || ౧౪ ||",
            "తాం మ॒ ఆవ॑హ॒ జాత॑వేదో ల॒క్ష్మీమన॑పగా॒మినీ”మ్ |",
            "యస్యా॒o హి॑రణ్య॒o ప్రభూ॑త॒o గావో॑ దా॒స్యోఽశ్వా”న్వి॒న్దేయ॒o పురు॑షాన॒హమ్ || ౧౫ ||",
            "యః శుచి॒: ప్రయ॑తో భూ॒త్వా జు॒హుయా॑దాజ్య॒ మన్వ॑హమ్ |",
            "శ్రియ॑: ప॒ఞ్చద॑శర్చ॒o చ శ్రీ॒కామ॑: సత॒తం జ॑పేత్ ||",
            "ఓం శాన్తి॒: శాన్తి॒: శాన్తి॑: ||",
          ],
          english: [
            "hira̍ṇyavarṇā̱ṃ hari̍ṇīṃ su̱varṇa̍raja̱tasra̍jām |",
            "ca̱ndrāṃ hi̱raṇma̍yīṃ la̱kṣmīṃ jāta̍vedo ma̱ āva̍ha || 1 ||",
            "tāṃ ma̱ āva̍ha̱ jāta̍vedo la̱kṣmīmana̍pagā̱minī̎m |",
            "yasyā̱ṃ hira̍ṇyaṃ vi̱ndeya̱ṃ gāmaśva̱ṃ puru̍ṣāna̱ham || 2 ||",
            "a̱śva̱pū̱rvāṃ ra̍thama̱dhyāṃ ha̱stinā̍dapra̱bodhi̍nīm |",
            "śriya̍ṃ de̱vīmupa̍hvaye̱ śrīrmā̍de̱vīrju̍ṣatām || 3 ||",
            "kā̱ṃ so̎smi̱tāṃ hira̍ṇyaprā̱kārā̍mā̱rdrāṃ jvala̍ntīṃ tṛ̱ptāṃ ta̱rpaya̍ntīm |",
            "pa̱dme̱ sthi̱tāṃ pa̱dmava̍rṇā̱ṃ tāmi̱hopa̍hvaye̱ śriyam || 4 ||",
            "ca̱ndrāṃ pra̍bhā̱sāṃ ya̱śasā̱ jvala̍ntī̱ṃ śriya̍ṃ lo̱ke de̱vaju̍ṣṭāmudā̱rām |",
            "tāṃ pa̱dminī̍mī̱ṃ śara̍ṇama̱haṃ prapa̍dye’la̱kṣmīrme̍ naśyatā̱ṃ tvāṃ vṛ̍ṇe || 5 ||",
            "ā̱di̱tyava̍rṇe̱ tapa̱so’dhi̍jā̱to vana̱spati̱stava̍ vṛ̱kṣo’tha bi̱lvaḥ |",
            "tasya̱ phalā̍ni̱ tapa̱sā nu̍dantu mā̱yānta̍rā̱yāśca̍ bā̱hyā a̍la̱kṣmīḥ || 6 ||",
            "upai̍tu̱ māṃ de̍vasa̱khaḥ kī̱rtiśca̱ maṇi̍nā sa̱ha |",
            "prā̱du̱rbhū̱to’smi̍ rāṣṭre̱’smin kī̱rtimṛ̍ddhiṃ da̱dātu̍ me || 7 ||",
            "kṣutpi̍pā̱sāma̍lāṃ jye̱ṣṭhāma̍la̱kṣmīṃ nā̍śayā̱myaham |",
            "abhū̍ti̱masa̍mṛddhi̱ṃ ca sarvā̱ṃ nirṇu̍da me̱ gṛhā̍t || 8 ||",
            "ga̱ndha̱dvā̱rāṃ du̍rādha̱rṣā̱ṃ ni̱tyapu̍ṣṭāṃ karī̱ṣiṇī̎m |",
            "ī̱śvarī̍gṃ sarva̍bhūtā̱nā̱ṃ tāmi̱hopa̍hvaye̱ śriyam || 9 ||",
            "mana̍sa̱: kāma̱mākū̍tiṃ vā̱caḥ sa̱tyama̍śīmahi |",
            "pa̱śū̱nāṃ rū̱pamanna̍sya̱ mayi̱ śrīḥ śra̍yatā̱ṃ yaśa̍: || 10 ||",
            "ka̱rdame̍na pra̍jābhū̱tā̱ ma̱yi̱ sambha̍va ka̱rdama |",
            "śriya̍ṃ vā̱saya̍ me ku̱le mā̱tara̍ṃ padma̱māli̍nīm || 11 ||",
            "āpa̍: sṛ̱jantu̍ sni̱gdhā̱ni̱ ci̱klī̱ta va̍sa me̱ gṛhe |",
            "ni ca̍ de̱vīṃ mā̱tara̱ṃ śriya̍ṃ vā̱saya̍ me ku̱le || 12 ||",
            "ā̱rdrāṃ pu̱ṣkari̍ṇīṃ pu̱ṣṭi̱ṃ pi̱ṅga̱lāṃ pa̍dmamā̱linīm |",
            "ca̱ndrāṃ hi̱raṇma̍yīṃ la̱kṣmīṃ jāta̍vedo ma̱ āva̍ha || 13 ||",
            "ā̱rdrāṃ ya̱: kari̍ṇīṃ ya̱ṣṭi̱ṃ su̱va̱rṇāṃ he̍mamā̱linīm |",
            "sū̱ryāṃ hi̱raṇma̍yīṃ la̱kṣmī̱ṃ jāta̍vedo ma̱ āvaha || 14 ||",
            "tāṃ ma̱ āva̍ha̱ jāta̍vedo la̱kṣmīmana̍pagā̱minī̎m |",
            "yasyā̱ṃ hi̍raṇya̱ṃ prabhū̍ta̱ṃ gāvo̍ dā̱syo’śvā̎nvi̱ndeya̱ṃ puru̍ṣāna̱ham || 15 ||",
            "yaḥ śuci̱: praya̍to bhū̱tvā ju̱huyā̍dājya̱ manva̍ham |",
            "śriya̍: pa̱ñcada̍śarca̱ṃ ca śrī̱kāma̍: sata̱taṃ ja̍pet ||",
            "oṃ śānti̱: śānti̱: śānti̍: ||",
          ],
          meaning:
            "The Sri Suktam invokes Goddess Lakshmi — golden-hued, radiant, seated on the lotus — praying for her presence, prosperity, cattle, gold and progeny, and for the banishing of alakshmi (misfortune, poverty and inauspiciousness) from one's home.",
        },
        {
          id: "purusha-suktam",
          title: "పురుష సూక్తం",
          titleEn: "Purusha Suktam",
          note: "తైత్తిరీయ ఆరణ్యకం · Source: Stotranidhi (with svara markings).",
          telugu: [
            "ఓమ్ | తచ్ఛ॒oయోరావృ॑ణీమహే | గా॒తుం య॒జ్ఞాయ॑ |",
            "గా॒తుం య॒జ్ఞప॑తయే | దైవీ” స్వ॒స్తిర॑స్తు నః |",
            "స్వ॒స్తిర్మాను॑షేభ్యః | ఊ॒ర్ధ్వం జి॑గాతు భేష॒జమ్ |",
            "శం నో॑ అస్తు ద్వి॒పదే” | శం చతు॑ష్పదే ||",
            "ఓం శాన్తి॒: శాన్తి॒: శాన్తి॑: ||",
            "స॒హస్ర॑శీర్షా॒ పురు॑షః |",
            "స॒హ॒స్రా॒క్షః స॒హస్ర॑పాత్ |",
            "స భూమి॑o వి॒శ్వతో॑ వృ॒త్వా |",
            "అత్య॑తిష్ఠద్దశాఙ్గు॒లమ్ || ౧ ||",
            "పురు॑ష ఏ॒వేదగ్ం సర్వమ్” |",
            "యద్భూ॒తం యచ్చ॒ భవ్యమ్” |",
            "ఉ॒తామృ॑త॒త్వస్యేశా॑నః |",
            "యదన్నే॑నాతి॒రోహ॑తి || ౨ ||",
            "ఏ॒తావా॑నస్య మహి॒మా |",
            "అతో॒ జ్యాయాగ్॑శ్చ॒ పూరు॑షః |",
            "పాదో”ఽస్య॒ విశ్వా॑ భూ॒తాని॑ |",
            "త్రి॒పాద॑స్యా॒మృత॑o ది॒వి || ౩ ||",
            "త్రి॒పాదూ॒ర్ధ్వ ఉదై॒త్పురు॑షః |",
            "పాదో”ఽస్యే॒హాఽఽభ॑వా॒త్పున॑: |",
            "తతో॒ విష్వ॒ఙ్వ్య॑క్రామత్ |",
            "సా॒శ॒నా॒న॒శ॒నే అ॒భి || ౪ ||",
            "తస్మా”ద్వి॒రాడ॑జాయత |",
            "వి॒రాజో॒ అధి॒ పూరు॑షః |",
            "స జా॒తో అత్య॑రిచ్యత |",
            "ప॒శ్చాద్భూమి॒మథో॑ పు॒రః || ౫ ||",
            "యత్పురు॑షేణ హ॒విషా” |",
            "దే॒వా య॒జ్ఞమత॑న్వత |",
            "వ॒స॒న్తో అ॑స్యాఽఽసీ॒దాజ్యమ్” |",
            "గ్రీ॒ష్మ ఇ॒ధ్మః శ॒రద్ధ॒విః || ౬ ||",
            "స॒ప్తాస్యా॑ఽఽసన్పరి॒ధయ॑: |",
            "త్రిః స॒ప్త స॒మిధ॑: కృ॒తాః |",
            "దే॒వా యద్య॒జ్ఞం త॑న్వా॒నాః |",
            "అబ॑ధ్న॒న్పురు॑షం ప॒శుమ్ || ౭ ||",
            "తం య॒జ్ఞం బ॒ర్హిషి॒ ప్రౌక్షన్న్॑ |",
            "పురు॑షం జా॒తమ॑గ్ర॒తః |",
            "తేన॑ దే॒వా అయ॑జన్త |",
            "సా॒ధ్యా ఋష॑యశ్చ॒ యే || ౮ ||",
            "తస్మా”ద్య॒జ్ఞాత్ స॑ర్వ॒హుత॑: |",
            "సంభృ॑తం పృషదా॒జ్యమ్ |",
            "ప॒శూగ్‍స్తాగ్‍శ్చ॑క్రే వాయ॒వ్యాన్॑ |",
            "ఆ॒ర॒ణ్యాన్ గ్రా॒మ్యాశ్చ॒ యే || ౯ ||",
            "తస్మా”ద్య॒జ్ఞాత్ స॑ర్వ॒హుత॑: |",
            "ఋచ॒: సామా॑ని జజ్ఞిరే |",
            "ఛన్దాగ్॑oసి జజ్ఞిరే॒ తస్మా”త్ |",
            "యజు॒స్తస్మా॑దజాయత || ౧౦ ||",
            "తస్మా॒దశ్వా॑ అజాయన్త |",
            "యే కే చో॑భ॒యాద॑తః |",
            "గావో॑ హ జజ్ఞిరే॒ తస్మా”త్ |",
            "తస్మా”జ్జా॒తా అ॑జా॒వయ॑: || ౧౧ ||",
            "యత్పురు॑ష॒o వ్య॑దధుః |",
            "క॒తి॒ధా వ్య॑కల్పయన్ |",
            "ముఖ॒o కిమ॑స్య॒ కౌ బా॒హూ |",
            "కావూ॒రూ పాదా॑వుచ్యేతే || ౧౨ ||",
            "బ్రా॒హ్మ॒ణో”ఽస్య॒ ముఖ॑మాసీత్ |",
            "బా॒హూ రా॑జ॒న్య॑: కృ॒తః |",
            "ఊ॒రూ తద॑స్య॒ యద్వైశ్య॑: |",
            "ప॒ద్భ్యాగ్ం శూ॒ద్రో అ॑జాయత || ౧౩ ||",
            "చ॒న్ద్రమా॒ మన॑సో జా॒తః |",
            "చక్షో॒: సూర్యో॑ అజాయత |",
            "ముఖా॒దిన్ద్ర॑శ్చా॒గ్నిశ్చ॑ |",
            "ప్రా॒ణాద్వా॒యుర॑జాయత || ౧౪ ||",
            "నాభ్యా॑ ఆసీద॒న్తరి॑క్షమ్ |",
            "శీ॒ర్ష్ణో ద్యౌః సమ॑వర్తత |",
            "ప॒ద్భ్యాం భూమి॒ర్దిశ॒: శ్రోత్రా”త్ |",
            "తథా॑ లో॒కాగ్ం అ॑కల్పయన్ || ౧౫ ||",
            "వేదా॒హమే॒తం పురు॑షం మ॒హాన్తమ్” |",
            "ఆ॒ది॒త్యవ॑ర్ణ॒o తమ॑స॒స్తు పా॒రే |",
            "సర్వా॑ణి రూ॒పాణి॑ వి॒చిత్య॒ ధీర॑: |",
            "నామా॑ని కృ॒త్వాఽభి॒వద॒న్॒ యదాస్తే” || ౧౬ ||",
            "ధా॒తా పు॒రస్తా॒ద్యము॑దాజ॒హార॑ |",
            "శ॒క్రః ప్రవి॒ద్వాన్ప్ర॒దిశ॒శ్చత॑స్రః |",
            "తమే॒వం వి॒ద్వాన॒మృత॑ ఇ॒హ భ॑వతి |",
            "నాన్యః పన్థా॒ అయ॑నాయ విద్యతే || ౧౭ ||",
            "య॒జ్ఞేన॑ య॒జ్ఞమ॑యజన్త దే॒వాః |",
            "తాని॒ ధర్మా॑ణి ప్రథ॒మాన్యా॑సన్ |",
            "తే హ॒ నాక॑o మహి॒మాన॑: సచన్తే |",
            "యత్ర॒ పూర్వే॑ సా॒ధ్యాః సన్తి॑ దే॒వాః || ౧౮ ||",
            "అ॒ద్భ్యః సంభూ॑తః పృథి॒వ్యై రసా”చ్చ |",
            "వి॒శ్వక॑ర్మణ॒: సమ॑వర్త॒తాధి॑ |",
            "తస్య॒ త్వష్టా॑ వి॒దధ॑ద్రూ॒పమే॑తి |",
            "తత్పురు॑షస్య॒ విశ్వ॒మాజా॑న॒మగ్రే” || ౧౯ ||",
            "వేదా॒హమే॒తం పురు॑షం మ॒హాన్తమ్” |",
            "ఆ॒ది॒త్యవ॑ర్ణ॒o తమ॑స॒: పర॑స్తాత్ |",
            "తమే॒వం వి॒ద్వాన॒మృత॑ ఇ॒హ భ॑వతి |",
            "నాన్యః పన్థా॑ విద్య॒తేఽయ॑నాయ || ౨౦ ||",
            "ప్ర॒జాప॑తిశ్చరతి॒ గర్భే॑ అ॒న్తః |",
            "అ॒జాయ॑మానో బహు॒ధా విజా॑యతే |",
            "తస్య॒ ధీరా॒: పరి॑జానన్తి॒ యోనిమ్” |",
            "మరీ॑చీనాం ప॒దమి॑చ్ఛన్తి వే॒ధస॑: || ౨౧ ||",
            "యో దే॒వేభ్య॒ ఆత॑పతి |",
            "యో దే॒వానా”o పు॒రోహి॑తః |",
            "పూర్వో॒ యో దే॒వేభ్యో॑ జా॒తః |",
            "నమో॑ రు॒చాయ॒ బ్రాహ్మ॑యే || ౨౨ ||",
            "రుచ॑o బ్రా॒హ్మం జ॒నయ॑న్తః |",
            "దే॒వా అగ్రే॒ తద॑బ్రువన్ |",
            "యస్త్వై॒వం బ్రా”హ్మ॒ణో వి॒ద్యాత్ |",
            "తస్య॑ దే॒వా అస॒న్ వశే” || ౨౩ ||",
            "హ్రీశ్చ॑ తే ల॒క్ష్మీశ్చ॒ పత్న్యౌ” |",
            "అ॒హో॒రా॒త్రే పా॒ర్శ్వే |",
            "నక్ష॑త్రాణి రూ॒పమ్ |",
            "అ॒శ్వినౌ॒ వ్యాత్తమ్” |",
            "ఇ॒ష్టం మ॑నిషాణ |",
            "అ॒ముం మ॑నిషాణ |",
            "సర్వ॑o మనిషాణ || ౨౪ ||",
            "ఓమ్ | తచ్ఛ॒oయోరావృ॑ణీమహే |",
            "గా॒తుం య॒జ్ఞాయ॑ | గా॒తుం య॒జ్ఞప॑తయే |",
            "దైవీ” స్వ॒స్తిర॑స్తు నః | స్వ॒స్తిర్మాను॑షేభ్యః |",
            "ఊ॒ర్ధ్వం జి॑గాతు భేష॒జమ్ |",
            "శం నో॑ అస్తు ద్వి॒పదే” | శం చతు॑ష్పదే ||",
            "ఓం శాన్తి॒: శాన్తి॒: శాన్తి॑: ||",
          ],
          english: [
            "oṃ taccha̱ṃ yorāvṛ̍ṇīmahe | gā̱tuṃ ya̱jñāya̍ |",
            "gā̱tuṃ ya̱jñapa̍taye | daivī̎: sva̱stira̍stu naḥ |",
            "sva̱stirmānu̍ṣebhyaḥ | ū̱rdhvaṃ ji̍gātu bheṣa̱jam |",
            "śanno̍ astu dvi̱pade̎ | śaṃ catu̍ṣpade ||",
            "oṃ śānti̱: śānti̱: śānti̍: ||",
            "sa̱hasra̍śīrṣā̱ puru̍ṣaḥ |",
            "sa̱ha̱srā̱kṣaḥ sa̱hasra̍pāt |",
            "sa bhūmi̍ṃ vi̱śvato̍ vṛ̱tvā |",
            "atya̍tiṣṭhaddaśāṅgu̱lam || 1 ||",
            "puru̍ṣa e̱vedagṃ sarvam̎ |",
            "yadbhū̱taṃ yacca̱ bhavyam̎ |",
            "u̱tāmṛ̍ta̱tvasyeśā̍naḥ |",
            "ya̱danne̍nāti̱roha̍ti || 2 ||",
            "e̱tāvā̍nasya mahi̱mā |",
            "ato̱ jyāyāg̍śca̱ pūru̍ṣaḥ |",
            "pādo̎’sya̱ viśvā̍ bhū̱tāni̍ |",
            "tri̱pāda̍syā̱mṛta̍ṃ di̱vi || 3 ||",
            "tri̱pādū̱rdhva udai̱tpuru̍ṣaḥ |",
            "pādo̎’sye̱hā”bha̍vā̱tpuna̍: |",
            "tato̱ viṣva̱ṅvya̍krāmat |",
            "sā̱śa̱nā̱na̱śa̱ne a̱bhi || 4 ||",
            "tasmā̎dvi̱rāḍa̍jāyata |",
            "vi̱rājo̱ adhi̱ pūru̍ṣaḥ |",
            "sa jā̱to atya̍ricyata |",
            "pa̱ścādbhūmi̱matho̍ pu̱raḥ || 5 ||",
            "yatpuru̍ṣeṇa ha̱viṣā̎ |",
            "de̱vā ya̱jñamata̍nvata |",
            "va̱sa̱nto a̍syāsī̱dājyam̎ |",
            "grī̱ṣma i̱dhmaśśa̱raddha̱viḥ || 6 ||",
            "sa̱ptāsyā̍sanpari̱dhaya̍: |",
            "triḥ sa̱pta sa̱midha̍: kṛ̱tāḥ |",
            "de̱vā yadya̱jñaṃ ta̍nvā̱nāḥ |",
            "aba̍dhna̱npuru̍ṣaṃ pa̱śum || 7 ||",
            "taṃ ya̱jñaṃ ba̱rhiṣi̱ praukṣan̍ |",
            "puru̍ṣaṃ jā̱tama̍gra̱taḥ |",
            "tena̍ de̱vā aya̍janta |",
            "sā̱dhyā ṛṣa̍yaśca̱ ye || 8 ||",
            "tasmā̎dya̱jñātsa̍rva̱huta̍: |",
            "sambhṛ̍taṃ pṛṣadā̱jyam |",
            "pa̱śūgstāgśca̍kre vāya̱vyān̍ |",
            "ā̱ra̱ṇyāngrā̱myāśca̱ ye || 9 ||",
            "tasmā̎dya̱jñātsa̍rva̱huta̍: |",
            "ṛca̱: sāmā̍ni jajñire |",
            "chandāg̍ṃsi jajñire̱ tasmā̎t |",
            "yaju̱stasmā̍dajāyata || 10 ||",
            "tasmā̱daśvā̍ ajāyanta |",
            "ye ke co̍bha̱yāda̍taḥ |",
            "gāvo̍ ha jajñire̱ tasmā̎t |",
            "tasmā̎jjā̱tā a̍jā̱vaya̍: || 11 ||",
            "yatpuru̍ṣa̱ṃ vya̍dadhuḥ |",
            "ka̱ti̱dhā vya̍kalpayan |",
            "mukha̱ṃ kima̍sya̱ kau bā̱hū |",
            "kāvū̱rū pādā̍vucyete || 12 ||",
            "brā̱hma̱ṇo̎’sya̱ mukha̍māsīt |",
            "bā̱hū rā̍ja̱nya̍: kṛ̱taḥ |",
            "ū̱rū tada̍sya̱ yadvaiśya̍: |",
            "pa̱dbhyāgṃ śū̱dro a̍jāyata || 13 ||",
            "ca̱ndramā̱ mana̍so jā̱taḥ |",
            "cakṣo̱: sūryo̍ ajāyata |",
            "mukhā̱dindra̍ścā̱gniśca̍ |",
            "prā̱ṇādvā̱yura̍jāyata || 14 ||",
            "nābhyā̍ āsīda̱ntari̍kṣam |",
            "śī̱rṣṇo dyauḥ sama̍vartata |",
            "pa̱dbhyāṃ bhūmi̱rdiśa̱: śrotrā̎t |",
            "tathā̍ lo̱kāgṃ a̍kalpayan || 15 ||",
            "vedā̱hame̱taṃ puru̍ṣaṃ ma̱hāntam̎ |",
            "ā̱di̱tyava̍rṇa̱ṃ tama̍sa̱stu pā̱re |",
            "sarvā̍ṇi rū̱pāṇi̍ vi̱citya̱ dhīra̍: |",
            "nāmā̍ni kṛ̱tvā’bhi̱vada̱ṉ yadāste̎ || 16 ||",
            "dhā̱tā pu̱rastā̱dyamu̍dāja̱hāra̍ |",
            "śa̱kraḥ pravi̱dvānpra̱diśa̱ścata̍sraḥ |",
            "tame̱vaṃ vi̱dvāna̱mṛta̍ i̱ha bha̍vati |",
            "nānyaḥ panthā̱ aya̍nāya vidyate || 17 ||",
            "ya̱jñena̍ ya̱jñama̍yajanta de̱vāḥ |",
            "tāni̱ dharmā̍ṇi pratha̱mānyā̍san |",
            "te ha̱ nāka̍ṃ mahi̱māna̍: sacante |",
            "yatra̱ pūrve̍ sā̱dhyāḥ santi̍ de̱vāḥ || 18 ||",
            "a̱dbhyaḥ sambhū̍taḥ pṛthi̱vyai rasā̎cca |",
            "vi̱śvaka̍rmaṇa̱: sama̍varta̱tādhi̍ |",
            "tasya̱ tvaṣṭā̍ vi̱dadha̍drū̱pame̍ti |",
            "tatpuru̍ṣasya̱ viśva̱mājā̍na̱magre̎ || 19 ||",
            "vedā̱hame̱taṃ puru̍ṣaṃ ma̱hāntam̎ |",
            "ā̱di̱tyava̍rṇa̱ṃ tama̍sa̱: para̍stāt |",
            "tame̱vaṃ vi̱dvāna̱mṛta̍ i̱ha bha̍vati |",
            "nānyaḥ panthā̍ vidya̱teya̎nāya || 20 ||",
            "pra̱jāpa̍tiścarati̱ garbhe̍ a̱ntaḥ |",
            "a̱jāya̍māno bahu̱dhā vijā̍yate |",
            "tasya̱ dhīrā̱: pari̍jānanti̱ yonim̎ |",
            "marī̍cīnāṃ pa̱dami̍cchanti ve̱dhasa̍: || 21 ||",
            "yo de̱vebhya̱ āta̍pati |",
            "yo de̱vānā̎ṃ pu̱rohi̍taḥ |",
            "pūrvo̱ yo de̱vebhyo̍ jā̱taḥ |",
            "namo̍ ru̱cāya̱ brāhma̍ye || 22 ||",
            "ruca̍ṃ brā̱hmaṃ ja̱naya̍ntaḥ |",
            "de̱vā agre̱ tada̍bruvan |",
            "yastvai̱vaṃ brā̎hma̱ṇo vi̱dyāt |",
            "tasya̍ de̱vā asa̱n vaśe̎ || 23 ||",
            "hrīśca̍ te la̱kṣmīśca̱ patnyau̎ |",
            "a̱ho̱rā̱tre pā̱rśve |",
            "nakṣa̍trāṇi rū̱pam |",
            "a̱śvinau̱ vyāttam̎ |",
            "i̱ṣṭaṃ ma̍niṣāṇa |",
            "a̱muṃ ma̍niṣāṇa |",
            "sarva̍ṃ maniṣāṇa || 24 ||",
            "oṃ taccha̱ṃ yorāvṛ̍ṇīmahe |",
            "gā̱tuṃ ya̱jñāya̍ | gā̱tuṃ ya̱jñapa̍taye |",
            "daivī̎: sva̱stira̍stu naḥ | sva̱stirmānu̍ṣebhyaḥ |",
            "ū̱rdhvaṃ ji̍gātu bheṣa̱jam |",
            "śanno̍ astu dvi̱pade̎ | śaṃ catu̍ṣpade ||",
            "oṃ śānti̱: śānti̱: śānti̍: ||",
          ],
          meaning:
            "The Purusha Suktam (Rigveda 10.90 / Taittiriya Aranyaka) extols the Cosmic Being (Purusha) — thousand-headed, all-pervading — from whose sacrifice the entire creation arises: the Vedas, the beings, the varnas, the sun, moon, and worlds. It is a foundational hymn of daily Vedic worship.",
        },
      ],
    },
  ],
};

if (typeof window !== "undefined") window.ANUSHTANAM = ANUSHTANAM;
if (typeof module !== "undefined") module.exports = ANUSHTANAM;
